apiVersion: apps/v1
kind: Deployment
metadata:
  name: solarldes
  labels:
    app: solarldes
  namespace: solarldes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solarldes
  template:
    metadata:
      labels:
        app: solarldes
    spec:
      containers:
        - name: solarldes
          image: acrworkflow1686585388400.azurecr.io/image-workflow-1686585388400:latest
          ports:
            - containerPort: 8000